# Generated by Django 4.2.15 on 2024-08-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on', 'author']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_on', 'author']},
        ),
    ]
